/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testRoll_basic() {
        int num = 16;
        int expected = num;
        int[] actual = Library.roll(num);
        assertEquals(expected, actual.length);
    }

    @Test
    public void testContainsDuplicates_containsDupes() {
        int[] array = {1, 2, 3, 3, 5, 8};
        boolean expected = true;
        boolean actual = Library.containsDuplicates(array);
        assertEquals(expected, actual);
    }

    @Test
    public void testContainsDuplicates_notDupes() {
        int[] array = {1, 2, 4, 3, 5, 8};
        boolean actual = Library.containsDuplicates(array);
        assertEquals(false, actual);
    }

    @Test
    public void testAveragesOfArray_basic() {
        int[] array = {2, 4, 6, 8, 10, 12};
        int expected = 7;
        int actual = Library.averageArray(array);
        assertEquals(expected, actual);
    }

    @Test
    public void testAveragesOfArray_negatives() {
        int[] array = {-10, -10, -10, 0, 0, 0};
        int expected = -5;
        int actual = Library.averageArray(array);
        assertEquals(expected, actual);
    }

    @Test
    public void testAverageOfArrays_basic() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {1, 48, 12, 22, 55, 4, 5}
        };
        int expected = 3;
        int actual = Library.averageOfArrays(weeklyMonthTemperatures);
        assertEquals(expected, actual);
    }

    @Test
    public void testAverageOfArrays_goofed() {
        int[][] weeklyMonthTemperatures = {
                {1, 2, 1000, 45, 1},
                {2, 5, 1, 1, 1, -1, -1},
                {55, 54, 60, 53, 59, 57, 61},
                {1, 48, 12, 22, 55, 4, 5}
        };
        int expected = 1;
        int actual = Library.averageOfArrays(weeklyMonthTemperatures);
        assertEquals(expected, actual);
    }

}
